AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BabashkaLambda:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Tracing: "Active"
      MemorySize: 128
      Handler: not.used
      Runtime: provided # or provided.al2 for the newer Amazon Linux v2
      CodeUri: function.zip
      Policies:
        - AWSLambdaExecute

  BabashkaLambdaLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/BabashkaLambda
      RetentionInDays: 1
